/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { openDB } from "idb";

declare const self: ServiceWorkerGlobalScope;

const DB_NAME = "hyperlink-pwa-share";
const STORE_NAME = "shared-files";

// INTERCEPT SHARE TARGET POST REQUESTS ASAP
// This must be one of the first listeners to ensure it takes priority.
self.addEventListener("fetch", (event) => {
    const url = new URL(event.request.url);
    const normalizedPath = url.pathname.replace(/\/$/, "");
    const isSharePath = normalizedPath === "/send" || normalizedPath === "/api/share-target";

    if (event.request.method === "POST" && isSharePath) {
        event.respondWith(
            (async () => {
                try {
                    const formData = await event.request.formData();
                    const files = formData.getAll("media") as File[];
                    const title = formData.get("title") as string;
                    const text = formData.get("text") as string;
                    const shareUrl = formData.get("url") as string;

                    const db = await openDB(DB_NAME, 1, {
                        upgrade(db) {
                            db.createObjectStore(STORE_NAME);
                        },
                    });

                    const sharedData = {
                        files: files.map(f => ({
                            name: f.name,
                            type: f.type,
                            blob: f
                        })),
                        title,
                        text,
                        url: shareUrl,
                        timestamp: Date.now()
                    };

                    await db.put(STORE_NAME, sharedData, "latest");

                    // Redirect with success flag
                    return Response.redirect("/send?shared=true", 303);
                } catch (err: any) {
                    console.error("Share Target failed in SW:", err);
                    return Response.redirect(`/send?shared=error&msg=${encodeURIComponent(err.message)}`, 303);
                }
            })()
        );
    }
});

cleanupOutdatedCaches();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener("install", () => {
    self.skipWaiting();
});

self.addEventListener("activate", (event) => {
    event.waitUntil(self.clients.claim());
});

self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SKIP_WAITING") {
        self.skipWaiting();
    }
});
